import type { IPC } from "bare-stow/host";
import { createStowHost } from "@/client/rpc/stow-host";
import { resolveConfig } from "@/client/config-loader/resolve-config.expo";
import { getDeviceInfo } from "@/client/rpc/expo-device-info";
import { getClientLogger } from "@/logging";
import { RPCConnectionFailedError } from "@/utils/errors-client";
import type { RuntimeContext } from "@/schemas";

const logger = getClientLogger();

interface RNHarness {
  start(opts?: Record<string, unknown>): Promise<{ ipc: IPC }>;
}

let cachedRuntimeContext: RuntimeContext | undefined;

async function getRuntimeContext(): Promise<RuntimeContext> {
  if (cachedRuntimeContext) return cachedRuntimeContext;

  const { platform, deviceModel, deviceBrand } = await getDeviceInfo();
  cachedRuntimeContext = {
    runtime: "react-native",
    platform,
    deviceModel,
    deviceBrand,
  };
  return cachedRuntimeContext;
}

/**
 * Load the react-native stow harness generated by the Expo plugin at prebuild.
 * It boots the worker in a react-native-bare-kit Worklet and returns the IPC.
 */
function loadHarness(): RNHarness {
  let mod: unknown;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    mod = require("@qvac/sdk/worker.mobile.harness");
  } catch (error) {
    const message =
      "Failed to load mobile worker harness. Make sure the QVAC Expo plugin is configured " +
      "(add '@qvac/sdk/expo-plugin' to your app.json plugins array).";
    logger.error(message);
    throw new RPCConnectionFailedError(
      message,
      error instanceof Error ? error : undefined,
    );
  }
  const namespace = mod as { default?: RNHarness };
  return namespace.default ?? (mod as RNHarness);
}

const host = createStowHost({
  boot: async () => {
    const harness = loadHarness();
    return harness.start();
  },
  resolveConfig,
  getRuntimeContext,
});

export const getRPC = host.getRPC;
export const close = host.close;
export const createDuplexSession = host.createDuplexSession;
export const getWorkerLifeSignal = host.getWorkerLifeSignal;
