import { parseBuiltinSpecifier } from "@/commands/bundle/plugins";

function buildPluginImports(pluginSpecifiers: string[], sdkName: string) {
  const imports: string[] = [];
  const registrations: string[] = [];
  let varIndex = 0;

  for (const specifier of pluginSpecifiers) {
    const builtin = parseBuiltinSpecifier(specifier, sdkName);
    if (builtin) {
      imports.push(
        `import { ${builtin.exportName} } from "${sdkName}/${builtin.suffix}/plugin";`,
      );
      registrations.push(`registerPlugin(${builtin.exportName});`);
    } else {
      const varName = `customPlugin${varIndex++}`;
      imports.push(`import ${varName} from "${specifier}";`);
      registrations.push(`registerPlugin(${varName});`);
    }
  }

  const pluginsList = pluginSpecifiers.map((p) => `*   - ${p}`).join("\n");

  return {
    importsStr: imports.join("\n"),
    registrationsStr: registrations.join("\n"),
    pluginsList,
  };
}

export function generateWorkerEntry(
  pluginSpecifiers: string[],
  sdkName: string,
): string {
  const { importsStr, registrationsStr, pluginsList } = buildPluginImports(
    pluginSpecifiers,
    sdkName,
  );

  return `/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: @qvac/sdk/commands bundleSdk
 * Plugins: ${pluginSpecifiers.length}
 *
${pluginsList}
 */

import { initializeWorkerCore, ensureRPCSetup } from "${sdkName}/worker-core";
import { registerPlugin } from "${sdkName}/plugins";
import { getServerLogger } from "${sdkName}/logging";

${importsStr}

const { hasRPCConfig } = initializeWorkerCore();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: ${pluginSpecifiers.length}");

${registrationsStr}

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
`;
}

/**
 * Worker entry for the bare-stow harness (desktop): exports the `start(ipc,
 * ready)` the stow shim invokes, instead of the top-level `ensureRPCSetup`
 * used by the mobile BareKit bundle.
 */
export function generateWorkerStartEntry(
  pluginSpecifiers: string[],
  sdkName: string,
): string {
  const { importsStr, registrationsStr, pluginsList } = buildPluginImports(
    pluginSpecifiers,
    sdkName,
  );

  return `/**
 * QVAC SDK Worker Entry (auto-generated, bare-stow start contract)
 * Generated by: @qvac/sdk/commands bundleWorkerDesktop
 * Plugins: ${pluginSpecifiers.length}
 *
${pluginsList}
 */

import { initializeWorkerCore, startWorker } from "${sdkName}/worker-core";
import { registerPlugin } from "${sdkName}/plugins";
import { getServerLogger } from "${sdkName}/logging";

${importsStr}

export default function start(ipc, ready) {
  initializeWorkerCore();

${registrationsStr}

  getServerLogger().info("🐻 QVAC Worker (custom bundle)");
  return startWorker(ipc, ready);
}
`;
}
